/**
 * Approach: Frequency Map Comparison.
 * Intuitively, since string `t` is generated by shuffling `s` and adding 
 * one more character, counting the frequency of each character in `s` and 
 * then reducing it for `t` will leave the "difference" character with a 
 * negative count or as a new key.
 */
var findTheDifference = function(s, t) {
    let map = new Map();

    for (let char of s) {
        map.set(char, (map.get(char) || 0) + 1);
    }

    for (let char of t) {
        if (!map.has(char)) {
            return char;
        } else {
            map.set(char, map.get(char) - 1);
            if (map.get(char) < 0) {
                return char; 
            }
        }
    }
};